import IAddress from "./IAddress.js";
import ISocialMedia from "./ISocialMedia.js";
import IAgent from "./IAgent.js";
import IPhoneNumber from "./IPhoneNumber.js";
import ICustomerCategory from "./ICustomerCategory.js";
import { SemanticObject } from "@virtual-assembly/semantizer";
import { Semanticable } from "@virtual-assembly/semantizer";
import IConnector from "./IConnector.js";
import IGetterOptions from "./IGetterOptions.js";
export default abstract class Agent extends SemanticObject implements IAgent {
    protected connector: IConnector;
    protected constructor(parameters: {
        connector: IConnector;
        semanticId?: string;
        semanticType?: string;
        other?: Semanticable;
        localizations?: IAddress[];
        phoneNumbers?: IPhoneNumber[];
        emails?: string[];
        websites?: string[];
        socialMedias?: ISocialMedia[];
        logo?: string;
        customerCategoriesMembership?: ICustomerCategory[];
        doNotStore?: boolean;
    });
    removeLocalization(localization: IAddress): void;
    setLogo(logo: string): void;
    getLocalizations(options?: IGetterOptions): Promise<IAddress[]>;
    addEmailAddress(emailAddress: string): void;
    addPhoneNumber(phoneNumber: IPhoneNumber): void;
    getLogo(): string | undefined;
    setCustomerCategories(customerCategories: ICustomerCategory[]): void;
    getSocialMedias(options?: IGetterOptions): Promise<ISocialMedia[]>;
    setWebsites(emailAddresses: string[]): void;
    addSocialMedia(socialMedia: ISocialMedia): void;
    setPhoneNumbers(phoneNumbers: IPhoneNumber[]): void;
    setLocalizations(localizations: IAddress[]): void;
    getCustomerCategories(options?: IGetterOptions): Promise<ICustomerCategory[]>;
    getEmails(): string[];
    removeSocialMedia(socialMedia: ISocialMedia): void;
    removeCustomerCategory(customerCategory: ICustomerCategory): void;
    addLocalization(localization: IAddress): void;
    addWebsite(website: string): void;
    setEmails(emailAddresses: string[]): void;
    setSocialMedias(socialMedias: ISocialMedia[]): void;
    removePhoneNumber(phoneNumber: IPhoneNumber): void;
    removeWebsite(website: string): void;
    removeEmailAddress(emailAddress: string): void;
    addCustomerCategory(customerCategory: ICustomerCategory): void;
    getPhoneNumbers(options?: IGetterOptions): Promise<IPhoneNumber[]>;
    getWebsites(): string[];
}
//# sourceMappingURL=Agent.d.ts.map