import { Semanticable } from "@virtual-assembly/semantizer";
import DatasetExt from "rdf-ext/lib/Dataset.js";
import { DatasetCore } from '@rdfjs/types';
import IConnector from "./IConnector.js";
import IConnectorFactory, { IConnectorFactoryAddressCreateParams, IConnectorFactoryAllergenCharacteristicCreateParams, IConnectorFactoryCatalogCreateParams, IConnectorFactoryCatalogItemCreateParams, IConnectorFactoryCustomerCategoryCreateParams, IConnectorFactoryDeliveryOptionCreateParams, IConnectorFactoryOrganizationCreateParams, IConnectorFactoryLocalizedProductCreateParams, IConnectorFactoryNutrientCharacteristicCreateParams, IConnectorFactoryOfferCreateParams, IConnectorFactoryOpeningHoursSpecificationCreateParams, IConnectorFactoryOrderCreateParams, IConnectorFactoryOrderLineCreateParams, IConnectorFactoryPaymentMethodCreateParams, IConnectorFactoryPersonCreateParams, IConnectorFactoryPhoneNumberCreateParams, IConnectorFactoryPhysicalCharacteristicCreateParams, IConnectorFactoryPhysicalPlaceCreateParams, IConnectorFactoryPhysicalProductCreateParams, IConnectorFactoryPickupOptionCreateParams, IConnectorFactoryPlannedConsumptionFlowCreateParams, IConnectorFactoryPlannedLocalConsumptionFlowCreateParams, IConnectorFactoryPlannedLocalProductionFlowCreateParams, IConnectorFactoryPlannedLocalTransformationCreateParams, IConnectorFactoryPlannedProductionFlowCreateParams, IConnectorFactoryPlannedTransformationCreateParams, IConnectorFactoryPriceCreateParams, IConnectorFactoryProductBatchCreateParams, IConnectorFactoryQuantityCreateParams, IConnectorFactoryRealizedConsumptionFlowCreateParams, IConnectorFactoryRealizedProductionFlowCreateParams, IConnectorFactoryRealizedTransformationCreateParams, IConnectorFactoryRealStockCreateParams, IConnectorFactorySaleSessionCreateParams, IConnectorFactorySocialMediaCreateParams, IConnectorFactorySuppliedProductCreateParams, IConnectorFactoryTechnicalProductCreateParams, IConnectorFactoryTheoreticalStockCreateParams, IConnectorFactoryVirtualPlaceCreateParams, IConnectorFactoryCertificationCreateParams, IConnectorFactoryDeliveryStepCreateParams, IConnectorFactoryPickUpStepCreateParams, IConnectorFactoryRouteCreateParams, IConnectorFactoryTemplateSaleSessionCreateParams, IConnectorFactoryProductOptionCreateParams, IConnectorFactoryProductOptionValueCreateParams, IConnectorFactoryVariantCreateParams, IConnectorFactoryVariantCharacteristicCreateParams } from "./IConnectorFactory.js";
import IAddress from "./IAddress.js";
import IAllergenCharacteristic from "./IAllergenCharacteristic.js";
import ICatalog from "./ICatalog.js";
import ICatalogItem from "./ICatalogItem.js";
import ICustomerCategory from "./ICustomerCategory.js";
import IOrganization from "./IOrganization.js";
import IPrice from "./IPrice.js";
import ISuppliedProduct from "./ISuppliedProduct.js";
import INutrientCharacteristic from "./INutrientCharacteristic.js";
import IOffer from "./IOffer.js";
import IOrder from "./IOrder.js";
import IOrderLine from "./IOrderLine.js";
import IPerson from "./IPerson.js";
import IPhysicalCharacteristic from "./IPhysicalCharacteristic.js";
import IQuantity from "./IQuantity.js";
import ISaleSession from "./ISaleSession.js";
import IPlannedConsumptionFlow from "./IPlannedConsumptionFlow.js";
import IPlannedProductionFlow from "./IPlannedProductionFlow.js";
import IPlannedTransformation from "./IPlannedTransformation.js";
import IDeliveryOption from "./IDeliveryOption.js";
import IPhysicalPlace from "./IPhysicalPlace.js";
import ITechnicalProduct from "./ITechnicalProduct.js";
import IRealStock from "./IRealStock.js";
import ITheoreticalStock from "./ITheoreticalStock.js";
import IOpeningHoursSpecification from "./IOpeningHoursSpecification.js";
import IPhoneNumber from "./IPhoneNumber.js";
import ILocalizedProduct from "./ILocalizedProduct.js";
import IPaymentMethod from "./IPaymentMethod.js";
import IPhysicalProduct from "./IPhysicalProduct.js";
import IPickupOption from "./IPickupOption.js";
import IPlannedLocalConsumptionFlow from "./IPlannedLocalConsumptionFlow.js";
import IPlannedLocalProductionFlow from "./IPlannedLocalProductionFlow.js";
import IPlannedLocalTransformation from "./IPlannedLocalTransformation.js";
import IProductBatch from "./IProductBatch.js";
import IRealizedConsumptionFlow from "./IRealizedConsumptionFlow.js";
import IRealizedProductionFlow from "./IRealizedProductionFlow.js";
import IRealizedTransformation from "./IRealizedTransformation.js";
import ISocialMedia from "./ISocialMedia.js";
import IVirtualPlace from "./IVirtualPlace.js";
import ICertification from "./ICertification.js";
import IDeliveryStep from "./IDeliveryStep.js";
import IPickUpStep from "./IPickUpStep.js";
import IRoute from "./IRoute.js";
import ITemplateSaleSession from "./ITemplateSaleSession.js";
import IProductOption from "./IProductOption.js";
import IProductOptionValue from "./IProductOptionValue.js";
import IVariant from "./IVariant.js";
import IVariantCharacteristic from "./IVariantCharacteristic.js";
export default class ConnectorFactory implements IConnectorFactory {
    private connector;
    constructor(connector: IConnector);
    createFromRdfDatasetCore(dataset: DatasetCore): Semanticable | undefined;
    createAddress(parameters: IConnectorFactoryAddressCreateParams): IAddress;
    createAllergenCharacteristic(parameters: IConnectorFactoryAllergenCharacteristicCreateParams): IAllergenCharacteristic;
    createCatalog(parameters: IConnectorFactoryCatalogCreateParams): ICatalog;
    createCatalogItem(parameters: IConnectorFactoryCatalogItemCreateParams): ICatalogItem;
    createCertification(parameters: IConnectorFactoryCertificationCreateParams): ICertification;
    createCustomerCategory(parameters: IConnectorFactoryCustomerCategoryCreateParams): ICustomerCategory;
    createDeliveryOption(parameters: IConnectorFactoryDeliveryOptionCreateParams): IDeliveryOption;
    createDeliveryStep(parameters: IConnectorFactoryDeliveryStepCreateParams): IDeliveryStep;
    createLocalizedProduct(parameters: IConnectorFactoryLocalizedProductCreateParams): ILocalizedProduct;
    createNutrientCharacteristic(parameters: IConnectorFactoryNutrientCharacteristicCreateParams): INutrientCharacteristic;
    createOffer(parameters: IConnectorFactoryOfferCreateParams): IOffer;
    createOpeningHoursSpecification(parameters: IConnectorFactoryOpeningHoursSpecificationCreateParams): IOpeningHoursSpecification;
    createOrder(parameters: IConnectorFactoryOrderCreateParams): IOrder;
    createOrderLine(parameters: IConnectorFactoryOrderLineCreateParams): IOrderLine;
    createOrganization(parameters: IConnectorFactoryOrganizationCreateParams): IOrganization;
    createPaymentMethod(parameters: IConnectorFactoryPaymentMethodCreateParams): IPaymentMethod;
    createPerson(parameters: IConnectorFactoryPersonCreateParams): IPerson;
    createPhoneNumber(parameters: IConnectorFactoryPhoneNumberCreateParams): IPhoneNumber;
    createPhysicalCharacteristic(parameters: IConnectorFactoryPhysicalCharacteristicCreateParams): IPhysicalCharacteristic;
    createPhysicalPlace(parameters: IConnectorFactoryPhysicalPlaceCreateParams): IPhysicalPlace;
    createPhysicalProduct(parameters: IConnectorFactoryPhysicalProductCreateParams): IPhysicalProduct;
    createPickupOption(parameters: IConnectorFactoryPickupOptionCreateParams): IPickupOption;
    createPickUpStep(parameters: IConnectorFactoryPickUpStepCreateParams): IPickUpStep;
    createPlannedConsumptionFlow(parameters: IConnectorFactoryPlannedConsumptionFlowCreateParams): IPlannedConsumptionFlow;
    createPlannedLocalConsumptionFlow(parameters: IConnectorFactoryPlannedLocalConsumptionFlowCreateParams): IPlannedLocalConsumptionFlow;
    createPlannedLocalProductionFlow(parameters: IConnectorFactoryPlannedLocalProductionFlowCreateParams): IPlannedLocalProductionFlow;
    createPlannedLocalTransformation(parameters: IConnectorFactoryPlannedLocalTransformationCreateParams): IPlannedLocalTransformation;
    createPlannedProductionFlow(parameters: IConnectorFactoryPlannedProductionFlowCreateParams): IPlannedProductionFlow;
    createPlannedTransformation(parameters: IConnectorFactoryPlannedTransformationCreateParams): IPlannedTransformation;
    createPrice(parameters: IConnectorFactoryPriceCreateParams): IPrice;
    createProductBatch(parameters: IConnectorFactoryProductBatchCreateParams): IProductBatch;
    createProductOption(parameters: IConnectorFactoryProductOptionCreateParams): IProductOption;
    createProductOptionValue(parameters: IConnectorFactoryProductOptionValueCreateParams): IProductOptionValue;
    createQuantity(parameters: IConnectorFactoryQuantityCreateParams): IQuantity;
    createRealizedConsumptionFlow(parameters: IConnectorFactoryRealizedConsumptionFlowCreateParams): IRealizedConsumptionFlow;
    createRealizedProductionFlow(parameters: IConnectorFactoryRealizedProductionFlowCreateParams): IRealizedProductionFlow;
    createRealizedTransformation(parameters: IConnectorFactoryRealizedTransformationCreateParams): IRealizedTransformation;
    createRealStock(parameters: IConnectorFactoryRealStockCreateParams): IRealStock;
    createRoute(parameters: IConnectorFactoryRouteCreateParams): IRoute;
    createSaleSession(parameters: IConnectorFactorySaleSessionCreateParams): ISaleSession;
    createSocialMedia(parameters: IConnectorFactorySocialMediaCreateParams): ISocialMedia;
    createSuppliedProduct(parameters: IConnectorFactorySuppliedProductCreateParams): ISuppliedProduct;
    createTechnicalProduct(parameters: IConnectorFactoryTechnicalProductCreateParams): ITechnicalProduct;
    createTemplateSaleSession(parameters: IConnectorFactoryTemplateSaleSessionCreateParams): ITemplateSaleSession;
    createTheoreticalStock(parameters: IConnectorFactoryTheoreticalStockCreateParams): ITheoreticalStock;
    createVariant(parameters: IConnectorFactoryVariantCreateParams): IVariant;
    createVariantCharacteristic(parameters: IConnectorFactoryVariantCharacteristicCreateParams): IVariantCharacteristic;
    createVirtualPlace(parameters: IConnectorFactoryVirtualPlaceCreateParams): IVirtualPlace;
    createFromType(type: string): Semanticable | undefined;
    createFromRdfDataset(dataset: DatasetExt): Semanticable | undefined;
}
//# sourceMappingURL=ConnectorFactory.d.ts.map