import IPhysicalCharacteristic from "./IPhysicalCharacteristic.js";
import ISKOSConcept from "./ISKOSConcept.js";
import ICatalogItem from "./ICatalogItem.js";
import IDefinedProduct from "./IDefinedProduct.js";
import IAllergenCharacteristic from "./IAllergenCharacteristic.js";
import INutrientCharacteristic from "./INutrientCharacteristic.js";
import IQuantity from "./IQuantity.js";
import { SemanticObject } from "@virtual-assembly/semantizer";
import { Semanticable } from "@virtual-assembly/semantizer";
import IConnector from "./IConnector.js";
import IGetterOptions from "./IGetterOptions.js";
export default abstract class DefinedProduct extends SemanticObject implements IDefinedProduct {
    protected connector: IConnector;
    protected constructor(parameters: {
        connector: IConnector;
        semanticId?: string;
        semanticType?: string;
        other?: Semanticable;
        name?: string;
        description?: string;
        productType?: ISKOSConcept;
        quantity?: IQuantity;
        alcoholPercentage?: number;
        lifetime?: string;
        claims?: ISKOSConcept[];
        usageOrStorageConditions?: string;
        allergenCharacteristics?: IAllergenCharacteristic[];
        nutrientCharacteristics?: INutrientCharacteristic[];
        physicalCharacteristics?: IPhysicalCharacteristic[];
        geographicalOrigin?: ISKOSConcept;
        catalogItems?: ICatalogItem[];
        certifications?: ISKOSConcept[];
        natureOrigin?: ISKOSConcept[];
        partOrigin?: ISKOSConcept[];
        images?: string[];
        variants?: IDefinedProduct[];
        isVariantOf?: IDefinedProduct[];
        doNotStore?: boolean;
    });
    getCatalogItems(options?: IGetterOptions): Promise<ICatalogItem[]>;
    removeCatalogItem(catalogItem: ICatalogItem): void;
    removeAllergenCharacteristic(allergenCharacteristic: IAllergenCharacteristic): void;
    setVariants(variants: IDefinedProduct[]): void;
    addPhysicalCharacteristic(physicalCharacteristic: IPhysicalCharacteristic): void;
    setPhysicalCharacteristics(physicalCharacteristics: IPhysicalCharacteristic[]): void;
    getGeographicalOrigin(options?: IGetterOptions): Promise<ISKOSConcept | undefined>;
    addNatureOrigin(natureOrigin: ISKOSConcept): void;
    removePartOrigin(partOrigin: ISKOSConcept): void;
    setNutrientCharacteristics(nutrientCharacteristics: INutrientCharacteristic[]): void;
    getIsVariantOf(options?: IGetterOptions): Promise<IDefinedProduct[]>;
    getProductType(options?: IGetterOptions): Promise<ISKOSConcept | undefined>;
    addIsVariantOf(parent: IDefinedProduct): void;
    removeCertification(certification: ISKOSConcept): void;
    getUsageOrStorageConditions(): string | undefined;
    setCertifications(certifications: ISKOSConcept[]): void;
    setClaims(claims: ISKOSConcept[]): void;
    getNutrientCharacteristics(options?: IGetterOptions): Promise<INutrientCharacteristic[]>;
    removeImage(image: string): void;
    getClaims(options?: IGetterOptions): Promise<ISKOSConcept[]>;
    addCertification(certification: ISKOSConcept): void;
    removeNutrientCharacteristic(nutrientCharacteristic: INutrientCharacteristic): void;
    getPartOrigin(options?: IGetterOptions): Promise<ISKOSConcept[]>;
    removePhysicalCharacteristic(physicalCharacteristic: IPhysicalCharacteristic): void;
    setGeographicalOrigin(geographicalOrigin: ISKOSConcept): void;
    setIsVariantOf(parents: IDefinedProduct[]): void;
    setAlcoholPercentage(alcoholPercentage: number): void;
    setProductType(productType: ISKOSConcept): void;
    setUsageOrStorageConditions(usageOrStorageConditions: string): void;
    removeIsVariantOf(parent: IDefinedProduct): void;
    setName(name: string): void;
    setAllergenCharacteristics(allergenCharacteristics: IAllergenCharacteristic[]): void;
    setPartOrigins(partOrigin: ISKOSConcept[]): void;
    setDescription(description: string): void;
    getNatureOrigin(options?: IGetterOptions): Promise<ISKOSConcept[]>;
    getName(): string | undefined;
    getQuantity(): IQuantity | undefined;
    removeVariant(variant: IDefinedProduct): void;
    removeClaim(claim: ISKOSConcept): void;
    removeNatureOrigin(natureOrigin: ISKOSConcept): void;
    addClaim(claim: ISKOSConcept): void;
    getLifetime(): string | undefined;
    addCatalogItem(catalogItem: ICatalogItem): void;
    getCertifications(options?: IGetterOptions): Promise<ISKOSConcept[]>;
    addPartOrigin(partOrigin: ISKOSConcept): void;
    setCatalogItems(catalogItems: ICatalogItem[]): void;
    getAllergenCharacteristics(options?: IGetterOptions): Promise<IAllergenCharacteristic[]>;
    getDescription(): string | undefined;
    addVariant(variant: IDefinedProduct): void;
    getAlcoholPercentage(): number | undefined;
    addImage(image: string): void;
    getVariants(options?: IGetterOptions): Promise<IDefinedProduct[]>;
    addAllergenCharacteristic(allergenCharacteristic: IAllergenCharacteristic): void;
    addNutrientCharacteristic(nutrientCharacteristic: INutrientCharacteristic): void;
    setQuantity(quantity: IQuantity): void;
    setLifetime(lifetime: string): void;
    getImages(): string[];
    setNatureOrigins(natureOrigin: ISKOSConcept[]): void;
    getPhysicalCharacteristics(options?: IGetterOptions): Promise<IPhysicalCharacteristic[]>;
    setImages(image: string[]): void;
}
//# sourceMappingURL=DefinedProduct.d.ts.map