import ManagedByMainContact from "./ManagedByMainContact.js";
import IAddress from "./IAddress.js";
import ISuppliedProduct from "./ISuppliedProduct.js";
import ICatalogItem from "./ICatalogItem.js";
import ICustomerCategory from "./ICustomerCategory.js";
import ITechnicalProduct from "./ITechnicalProduct.js";
import IPerson from "./IPerson.js";
import IEnterprise from "./IEnterprise.js";
import ProductSupplier from "./ProductSupplier.js";
import Agent from "./Agent.js";
import Onboardable from "./Onboardable.js";
import ICatalog from "./ICatalog.js";
import { Semanticable } from "@virtual-assembly/semantizer";
import IConnector from "./IConnector.js";
import IGetterOptions from "./IGetterOptions.js";
export default class Enterprise extends Agent implements Onboardable, IEnterprise, ProductSupplier, ManagedByMainContact {
    constructor(parameters: {
        connector: IConnector;
        semanticId?: string;
        other?: Semanticable;
        name?: string;
        localizations?: IAddress[];
        description?: string;
        vatNumber?: string;
        customerCategories?: ICustomerCategory[];
        catalogs?: ICatalog[];
        catalogItems?: ICatalogItem[];
        suppliedProducts?: ISuppliedProduct[];
        technicalProducts?: ITechnicalProduct[];
        mainContact?: IPerson;
        logo?: string;
        affiliates?: IPerson[];
        doNotStore?: boolean;
    });
    setManagedCatalogItems(catalogItems: ICatalogItem[]): void;
    getDescription(): string | undefined;
    setAffiliates(affiliates: IPerson[]): void;
    getProposedTechnicalProducts(options?: IGetterOptions): Promise<ITechnicalProduct[]>;
    getMainContact(options?: IGetterOptions): Promise<IPerson | undefined>;
    proposeTechnicalProducts(technicalProducts: ITechnicalProduct): void;
    addCustomerCategory(customerCategory: ICustomerCategory): void;
    supplyProduct(suppliedProduct: ISuppliedProduct): void;
    unsupplyProduct(suppliedProduct: ISuppliedProduct): void;
    removeCustomerCategory(customerCategory: ICustomerCategory): void;
    unmanageCatalogItem(catalogItem: ICatalogItem): void;
    getMaintainedCatalogs(options?: IGetterOptions): Promise<ICatalog[]>;
    setSuppliedProducts(suppliedProducts: ISuppliedProduct[]): void;
    getManagedCatalogItems(options?: IGetterOptions): Promise<ICatalogItem[]>;
    maintainCatalog(catalog: ICatalog): void;
    getAffiliates(options?: IGetterOptions): Promise<IPerson[]>;
    getCustomerCategories(options?: IGetterOptions): Promise<ICustomerCategory[]>;
    unmaintainCatalog(catalog: ICatalog): void;
    setProposedTechnicalProducts(technicalProducts: ITechnicalProduct[]): void;
    setMainContact(mainContact: IPerson): void;
    setVatNumber(vatNumber: string): void;
    addAffiliate(affiliate: IPerson): void;
    getSuppliedProducts(options?: IGetterOptions): Promise<ISuppliedProduct[]>;
    getName(): string | undefined;
    getVatNumber(): string | undefined;
    setDescription(description: string): void;
    unproposeTechnicalProducts(technicalProducts: ITechnicalProduct): void;
    setName(name: string): void;
    removeAffiliate(affiliate: IPerson): void;
    manageCatalogItem(catalogItem: ICatalogItem): void;
    setCustomerCategories(customerCategories: ICustomerCategory[]): void;
}
//# sourceMappingURL=Enterprise.d.ts.map