import ISuppliedProduct from "./ISuppliedProduct.js";
import IPlannedLocalConsumptionFlow from "./IPlannedLocalConsumptionFlow.js";
import IQuantity from "./IQuantity.js";
import ITheoreticalStock from "./ITheoreticalStock.js";
import IPlannedLocalProductionFlow from "./IPlannedLocalProductionFlow.js";
import ILocalizedProduct from "./ILocalizedProduct.js";
import IPhysicalProduct from "./IPhysicalProduct.js";
import { SemanticObject } from "@virtual-assembly/semantizer";
import { Semanticable } from "@virtual-assembly/semantizer";
import IConnector from "./IConnector.js";
import IGetterOptions from "./IGetterOptions.js";
export default class LocalizedProduct extends SemanticObject implements ILocalizedProduct {
    protected connector: IConnector;
    constructor(parameters: {
        connector: IConnector;
        semanticId?: string;
        other?: Semanticable;
        name?: string;
        description?: string;
        quantity?: IQuantity;
        images?: string[];
        cost?: number;
        suppliedProducts?: ISuppliedProduct[];
        physicalProducts?: IPhysicalProduct[];
        theoreticalStocks?: ITheoreticalStock[];
        plannedLocalConsumptionFlows?: IPlannedLocalConsumptionFlow[];
        plannedLocalProductionFlows?: IPlannedLocalProductionFlow[];
        doNotStore?: boolean;
    });
    setSuppliedProducts(suppliedProducts: ISuppliedProduct[]): void;
    getDescription(): string | undefined;
    addPlannedLocalConsumptionFlow(consumptionFlow: IPlannedLocalConsumptionFlow): void;
    addTheoreticalStock(theoreticalStock: ITheoreticalStock): void;
    setTheoreticalStocks(theoreticalStocks: ITheoreticalStock[]): void;
    getTheoreticalStocks(options?: IGetterOptions): Promise<ITheoreticalStock[]>;
    removePlannedLocalProductionFlow(productionFlow: IPlannedLocalProductionFlow): void;
    removeTheoreticalStock(theoreticalStock: ITheoreticalStock): void;
    removePlannedLocalConsumptionFlow(consumptionFlow: IPlannedLocalConsumptionFlow): void;
    getQuantity(): IQuantity | undefined;
    getPlannedLocalConsumptionFlows(options?: IGetterOptions): Promise<IPlannedLocalConsumptionFlow[]>;
    addPlannedLocalProductionFlow(productionFlow: IPlannedLocalProductionFlow): void;
    setPlannedLocalProductionFlows(productionFlows: IPlannedLocalProductionFlow[]): void;
    addSuppliedProduct(suppliedProduct: ISuppliedProduct): void;
    setImages(image: string[]): void;
    removeImage(image: string): void;
    setPhysicalProducts(physicalProducts: IPhysicalProduct[]): void;
    removePhysicalProduct(physicalProduct: IPhysicalProduct): void;
    getPlannedLocalProductionFlows(options?: IGetterOptions): Promise<IPlannedLocalProductionFlow[]>;
    getImages(): string[];
    getCost(): number | undefined;
    getPhysicalProducts(options?: IGetterOptions): Promise<IPhysicalProduct[]>;
    addImage(image: string): void;
    setCost(cost: number): void;
    setQuantity(quantity: IQuantity): void;
    getName(): string | undefined;
    removeSuppliedProduct(suppliedProduct: ISuppliedProduct): void;
    setDescription(description: string): void;
    getSuppliedProducts(options?: IGetterOptions): Promise<ISuppliedProduct[]>;
    setName(name: string): void;
    setPlannedLocalConsumptionFlows(consumptionFlows: IPlannedLocalConsumptionFlow[]): void;
    addPhysicalProduct(physicalProduct: IPhysicalProduct): void;
}
//# sourceMappingURL=LocalizedProduct.d.ts.map