import IOrder from "./IOrder.js";
import IAgent from "./IAgent.js";
import ISKOSConcept from "./ISKOSConcept.js";
import ISaleSession from "./ISaleSession.js";
import IPaymentMethod from "./IPaymentMethod.js";
import IOrderLine from "./IOrderLine.js";
import { SemanticObject } from "@virtual-assembly/semantizer";
import { Semanticable } from "@virtual-assembly/semantizer";
import IConnector from "./IConnector.js";
import IGetterOptions from "./IGetterOptions.js";
export default class Order extends SemanticObject implements IOrder {
    protected connector: IConnector;
    constructor(parameters: {
        connector: IConnector;
        semanticId?: string;
        other?: Semanticable;
        number?: string;
        date?: string;
        saleSession?: ISaleSession;
        client?: IAgent;
        lines?: IOrderLine[];
        soldBy?: IAgent;
        fulfilmentStatus?: ISKOSConcept;
        orderStatus?: ISKOSConcept;
        paymentStatus?: ISKOSConcept;
        paymentMethod?: IPaymentMethod;
        doNotStore?: boolean;
    });
    setDate(date: string): void;
    getNumber(): string | undefined;
    setLines(lines: IOrderLine[]): void;
    setSaleSession(saleSession: ISaleSession): void;
    getSaleSession(options?: IGetterOptions): Promise<ISaleSession | undefined>;
    addLine(line: IOrderLine): void;
    setPaymentMethod(paymentMethod: IPaymentMethod): void;
    getClient(options?: IGetterOptions): Promise<IAgent | undefined>;
    getSoldBy(options?: IGetterOptions): Promise<IAgent | undefined>;
    setFulfilmentStatus(fulfilmentState: ISKOSConcept): void;
    getLines(options?: IGetterOptions): Promise<IOrderLine[]>;
    setPaymentStatus(paymentState: ISKOSConcept): void;
    setSoldBy(soldBy: IAgent): void;
    getPaymentMethod(options?: IGetterOptions): Promise<IPaymentMethod | undefined>;
    getFulfilmentStatus(options?: IGetterOptions): Promise<ISKOSConcept | undefined>;
    setOrderStatus(orderState: ISKOSConcept): void;
    setClient(client: IAgent): void;
    getPaymentStatus(options?: IGetterOptions): Promise<ISKOSConcept | undefined>;
    getDate(): string | undefined;
    setNumber(number: string): void;
    removeLine(line: IOrderLine): void;
    getOrderStatus(options?: IGetterOptions): Promise<ISKOSConcept | undefined>;
}
//# sourceMappingURL=Order.d.ts.map