import ProductSupplier from "./ProductSupplier.js";
import ICertification from "./ICertification.js";
import IAddress from "./IAddress.js";
import ITechnicalProduct from "./ITechnicalProduct.js";
import ICatalog from "./ICatalog.js";
import IPerson from "./IPerson.js";
import ISuppliedProduct from "./ISuppliedProduct.js";
import ITemplateSaleSession from "./ITemplateSaleSession.js";
import Agent from "./Agent.js";
import ICustomerCategory from "./ICustomerCategory.js";
import ManagedByMainContact from "./ManagedByMainContact.js";
import Onboardable from "./Onboardable.js";
import IOrganization from "./IOrganization.js";
import ICatalogItem from "./ICatalogItem.js";
import { Semanticable } from "@virtual-assembly/semantizer";
import IConnector from "./IConnector.js";
import IGetterOptions from "./IGetterOptions.js";
export default class Organization extends Agent implements Onboardable, ManagedByMainContact, ProductSupplier, IOrganization {
    constructor(parameters: {
        connector: IConnector;
        semanticId?: string;
        other?: Semanticable;
        name?: string;
        localizations?: IAddress[];
        description?: string;
        vatNumber?: string;
        customerCategories?: ICustomerCategory[];
        catalogs?: ICatalog[];
        catalogItems?: ICatalogItem[];
        suppliedProducts?: ISuppliedProduct[];
        technicalProducts?: ITechnicalProduct[];
        mainContact?: IPerson;
        logo?: string;
        templateSaleSessions?: ITemplateSaleSession[];
        customerCategoriesMembership?: ICustomerCategory[];
        certifications?: ICertification[];
        affiliates?: IPerson[];
        doNotStore?: boolean;
    });
    setMainContact(mainContact: IPerson): void;
    getMainContact(options?: IGetterOptions): Promise<IPerson | undefined>;
    getDescription(): string | undefined;
    getSuppliedProducts(options?: IGetterOptions): Promise<ISuppliedProduct[]>;
    setProposedTechnicalProducts(technicalProducts: ITechnicalProduct[]): void;
    setSuppliedProducts(suppliedProducts: ISuppliedProduct[]): void;
    getManagedCatalogItems(options?: IGetterOptions): Promise<ICatalogItem[]>;
    proposeTechnicalProducts(technicalProducts: ITechnicalProduct): void;
    manageCatalogItem(catalogItem: ICatalogItem): void;
    addTemplateSaleSession(templateSaleSession: ITemplateSaleSession): void;
    getMaintainedCatalogs(options?: IGetterOptions): Promise<ICatalog[]>;
    getAffiliates(options?: IGetterOptions): Promise<IPerson[]>;
    setManagedCatalogItems(catalogItems: ICatalogItem[]): void;
    addCertification(certification: ICertification): void;
    removeCertification(certification: ICertification): void;
    getCustomerCategories(options?: IGetterOptions): Promise<ICustomerCategory[]>;
    setCertifications(certifications: ICertification[]): void;
    unsupplyProduct(suppliedProduct: ISuppliedProduct): void;
    unmanageCatalogItem(catalogItem: ICatalogItem): void;
    setTemplateSaleSessions(templateSaleSessions: ITemplateSaleSession[]): void;
    removeAffiliate(affiliate: IPerson): void;
    getCertifications(options?: IGetterOptions): Promise<ICertification[]>;
    addAffiliate(affiliate: IPerson): void;
    maintainCatalog(catalog: ICatalog): void;
    getTemplateSaleSessions(options?: IGetterOptions): Promise<ITemplateSaleSession[]>;
    removeTemplateSaleSession(templateSaleSession: ITemplateSaleSession): void;
    setVatNumber(vatNumber: string): void;
    unmaintainCatalog(catalog: ICatalog): void;
    supplyProduct(suppliedProduct: ISuppliedProduct): void;
    getName(): string | undefined;
    getVatNumber(): string | undefined;
    setDescription(description: string): void;
    setName(name: string): void;
    unproposeTechnicalProducts(technicalProducts: ITechnicalProduct): void;
    setCustomerCategories(customerCategories: ICustomerCategory[]): void;
    setAffiliates(affiliates: IPerson[]): void;
    addCustomerCategory(customerCategory: ICustomerCategory): void;
    getProposedTechnicalProducts(options?: IGetterOptions): Promise<ITechnicalProduct[]>;
    removeCustomerCategory(customerCategory: ICustomerCategory): void;
}
//# sourceMappingURL=Organization.d.ts.map