import IGeoJsonFeature from "./IGeoJsonFeature.js";
import IOpeningHoursSpecification from "./IOpeningHoursSpecification.js";
import IAddress from "./IAddress.js";
import ISaleSession from "./ISaleSession.js";
import IPerson from "./IPerson.js";
import ITheoreticalStock from "./ITheoreticalStock.js";
import IPhysicalPlace from "./IPhysicalPlace.js";
import IPhoneNumber from "./IPhoneNumber.js";
import IRealStock from "./IRealStock.js";
import { SemanticObject } from "@virtual-assembly/semantizer";
import { Semanticable } from "@virtual-assembly/semantizer";
import IConnector from "./IConnector.js";
import IGetterOptions from "./IGetterOptions.js";
export default class PhysicalPlace extends SemanticObject implements IPhysicalPlace {
    protected connector: IConnector;
    constructor(parameters: {
        connector: IConnector;
        semanticId?: string;
        other?: Semanticable;
        name?: string;
        description?: string;
        hostedSaleSessions?: ISaleSession[];
        phoneNumbers?: IPhoneNumber[];
        openingHours?: IOpeningHoursSpecification[];
        address?: IAddress;
        mainContacts?: IPerson[];
        theoreticalStocks?: ITheoreticalStock[];
        realStocks?: IRealStock[];
        features?: IGeoJsonFeature[];
        doNotStore?: boolean;
    });
    getPhoneNumbers(options?: IGetterOptions): Promise<IPhoneNumber[]>;
    getDescription(): string | undefined;
    setHostedSaleSessions(saleSessions: ISaleSession[]): void;
    addOpeningHour(openingHour: IOpeningHoursSpecification): void;
    getAddress(options?: IGetterOptions): Promise<IAddress | undefined>;
    setFeatures(features: IGeoJsonFeature[]): void;
    setOpeningHours(openingHours: IOpeningHoursSpecification[]): void;
    addMainContact(mainContact: IPerson): void;
    getOpeningHours(options?: IGetterOptions): Promise<IOpeningHoursSpecification[]>;
    setTheoreticalStocks(theoreticalStocks: ITheoreticalStock[]): void;
    removeFeature(feature: IGeoJsonFeature): void;
    setPhoneNumbers(phoneNumbers: IPhoneNumber[]): void;
    getTheoreticalStocks(options?: IGetterOptions): Promise<ITheoreticalStock[]>;
    addRealStock(realStock: IRealStock): void;
    getHostedSaleSessions(options?: IGetterOptions): Promise<ISaleSession[]>;
    setRealStocks(realStocks: IRealStock[]): void;
    removeHostedSaleSession(): ISaleSession | undefined;
    removeTheoreticalStock(theoreticalStock: ITheoreticalStock): void;
    setMainContacts(mainContacts: IPerson[]): void;
    removeRealStock(realStock: IRealStock): void;
    setAddress(address: IAddress): void;
    getMainContacts(options?: IGetterOptions): Promise<IPerson[]>;
    getRealStocks(options?: IGetterOptions): Promise<IRealStock[]>;
    getName(): string | undefined;
    addTheoreticalStock(theoreticalStock: ITheoreticalStock): void;
    setDescription(description: string): void;
    addFeature(feature: IGeoJsonFeature): void;
    setName(name: string): void;
    addPhoneNumber(phoneNumber: IPhoneNumber): void;
    removeMainContact(mainContact: IPerson): void;
    removeOpeningHour(openingHour: IOpeningHoursSpecification): void;
    getFeatures(options?: IGetterOptions): Promise<IGeoJsonFeature[]>;
    addHostedSaleSession(saleSession: ISaleSession): void;
    removePhoneNumber(phoneNumber: IPhoneNumber): void;
}
//# sourceMappingURL=PhysicalPlace.d.ts.map