import IRealStock from "./IRealStock.js";
import IProductBatch from "./IProductBatch.js";
import IRealizedProductionFlow from "./IRealizedProductionFlow.js";
import IPhysicalProduct from "./IPhysicalProduct.js";
import IQuantity from "./IQuantity.js";
import ILocalizedProduct from "./ILocalizedProduct.js";
import IRealizedConsumptionFlow from "./IRealizedConsumptionFlow.js";
import { SemanticObject } from "@virtual-assembly/semantizer";
import { Semanticable } from "@virtual-assembly/semantizer";
import IConnector from "./IConnector.js";
import IGetterOptions from "./IGetterOptions.js";
export default class PhysicalProduct extends SemanticObject implements IPhysicalProduct {
    protected connector: IConnector;
    constructor(parameters: {
        connector: IConnector;
        semanticId?: string;
        other?: Semanticable;
        name?: string;
        description?: string;
        quantity?: IQuantity;
        images?: string[];
        localizedProducts?: ILocalizedProduct[];
        productBatches?: IProductBatch[];
        realStocks?: IRealStock[];
        realizedConsumptionFlows?: IRealizedConsumptionFlow[];
        realizedProductionFlows?: IRealizedProductionFlow[];
        doNotStore?: boolean;
    });
    setLocalizedProducts(localizedProducts: ILocalizedProduct[]): void;
    getDescription(): string | undefined;
    addRealStock(realStock: IRealStock): void;
    addRealizedProductionFlow(realizedProductionFlow: IRealizedProductionFlow): void;
    removeRealStock(realStock: IRealStock): void;
    removeRealizedProductionFlow(realizedProductionFlow: IRealizedProductionFlow): void;
    setRealizedProductionFlows(realizedProductionFlows: IRealizedProductionFlow[]): void;
    getRealizedProductionFlows(options?: IGetterOptions): Promise<IRealizedProductionFlow[]>;
    getProductBatches(options?: IGetterOptions): Promise<IProductBatch[]>;
    getRealStocks(options?: IGetterOptions): Promise<IRealStock[]>;
    setRealStocks(realStock: IRealStock[]): void;
    getQuantity(): IQuantity | undefined;
    setImages(image: string[]): void;
    removeRealizedConsumptionFlow(realizedConsumptionFlow: IRealizedConsumptionFlow): void;
    addLocalizedProduct(localizedProduct: ILocalizedProduct): void;
    removeImage(image: string): void;
    addProductBatch(productBatch: IProductBatch): void;
    getLocalizedProducts(options?: IGetterOptions): Promise<ILocalizedProduct[]>;
    getRealizedConsumptionFlows(options?: IGetterOptions): Promise<IRealizedConsumptionFlow[]>;
    getImages(): string[];
    addImage(image: string): void;
    removeLocalizedProduct(localizedProduct: ILocalizedProduct): void;
    setQuantity(quantity: IQuantity): void;
    getName(): string | undefined;
    setRealizedConsumptionFlows(realizedConsumptionFlows: IRealizedConsumptionFlow[]): void;
    setDescription(description: string): void;
    setName(name: string): void;
    removeProductBatch(productBatch: IProductBatch): void;
    setProductBatches(productBatches: IProductBatch[]): void;
    addRealizedConsumptionFlow(realizedConsumptionFlow: IRealizedConsumptionFlow): void;
}
//# sourceMappingURL=PhysicalProduct.d.ts.map