import IPhysicalCharacteristic from "./IPhysicalCharacteristic.js";
import ICatalogItem from "./ICatalogItem.js";
import ISKOSConcept from "./ISKOSConcept.js";
import INutrientCharacteristic from "./INutrientCharacteristic.js";
import IVariant from "./IVariant.js";
import DefinedProduct from "./DefinedProduct.js";
import IDefinedProduct from "./IDefinedProduct.js";
import IProductOption from "./IProductOption.js";
import IVariantCharacteristic from "./IVariantCharacteristic.js";
import IAllergenCharacteristic from "./IAllergenCharacteristic.js";
import IQuantity from "./IQuantity.js";
import { Semanticable } from "@virtual-assembly/semantizer";
import IConnector from "./IConnector.js";
import IGetterOptions from "./IGetterOptions.js";
export default class Variant extends DefinedProduct implements IVariant {
    constructor(parameters: {
        connector: IConnector;
        semanticId?: string;
        other?: Semanticable;
        name?: string;
        description?: string;
        productType?: ISKOSConcept;
        quantity?: IQuantity;
        alcoholPercentage?: number;
        lifetime?: string;
        claims?: ISKOSConcept[];
        usageOrStorageConditions?: string;
        allergenCharacteristics?: IAllergenCharacteristic[];
        nutrientCharacteristics?: INutrientCharacteristic[];
        physicalCharacteristics?: IPhysicalCharacteristic[];
        geographicalOrigin?: ISKOSConcept;
        catalogItems?: ICatalogItem[];
        certifications?: ISKOSConcept[];
        natureOrigin?: ISKOSConcept[];
        partOrigin?: ISKOSConcept[];
        images?: string[];
        variants?: IDefinedProduct[];
        isVariantOf?: IDefinedProduct[];
        variantCharacteristics?: IVariantCharacteristic[];
        referenceProductOptions?: IProductOption[];
        doNotStore?: boolean;
    });
    removeIsVariantOf(product: IDefinedProduct): void;
    setVariantCharacteristics(variantCharacteristics: IVariantCharacteristic[]): void;
    removeVariantCharacteristic(variantCharacteristic: IVariantCharacteristic): void;
    getVariantCharacteristics(options?: IGetterOptions): Promise<IVariantCharacteristic[]>;
    setIsVariantOf(products: IDefinedProduct[]): void;
    isVariantOf(options?: IGetterOptions): Promise<IDefinedProduct[]>;
    addIsVariantOf(product: IDefinedProduct): void;
    addVariantCharacteristic(variantCharacteristic: IVariantCharacteristic): void;
}
//# sourceMappingURL=Variant.d.ts.map